zippath: 'temp_data/'
asset:
  background: 'assets/datakoen-bg.jpg'
  icon: 'assets/datakoen-icon.png'
  home-markdown: 'assets/markdowns/home.md'
  map-explain: 'assets/markdowns/indomap-table-explain.md'