zippath: 'temp_data/'
asset:
  background: 'assets/datakoen-bg.jpg'
  icon: 'assets/datakoen-icon.png'
  home-markdown: 'assets/markdowns/home.md'
  map-opening: 'assets/markdowns/indomap-opening.md'
  map-explain: 'assets/markdowns/indomap-table-explain.md'
  templates-auto-slider: 'assets/templates/auto_slider.html'
  templates-human-slider: 'assets/templates/human_slider.html'