name: Fly Deployment

on:
  push:
    branches:
      - main
    tags:
        - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CRED}}'

      - name: Create Writable Directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/app/default
      
      - name: Copy VDB to Directory
        run: |
          gcloud storage cp gs://datakoen/test.txt $GITHUB_WORKSPACE/app/default/my_profile.txt
          gcloud storage cp -r gs://datakoen/about_me $GITHUB_WORKSPACE/app/default/
          ls -l app/default/about_me/

      - name: Install Fly.io CLI
        env:
          FLY_TOKEN: ${{ secrets.FLY_TOKEN }}
        run: |
          curl -L https://fly.io/install.sh | sh 
          export FLYCTL_INSTALL="/home/runner/.fly"
          export PATH="$FLYCTL_INSTALL/bin:$PATH"
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            export FLY_APP="dev-datakoen"
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            export FLY_APP="datakoen"
          fi
          flyctl secrets set TOGETHER_API_KEY="${{ secrets.TOGETHER_KEY }}" hf_token="${{ secrets.HF_TOKEN }}" --app $FLY_APP --access-token $FLY_TOKEN

          if flyctl apps list | grep -q "$FLY_APP"; then
              echo "App $FLY_APP exists. Redeploying..."
          else
              echo "App $FLY_APP does not exist. Creating..."
              flyctl apps create "$FLY_APP"
          fi

          flyctl deploy --config fly.toml --app "$FLY_APP" --access-token $FLY_TOKEN
