name: Fly Deployment

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CRED }}'

      - name: Install gcloud CLI
        run: |
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk
          gcloud auth activate-service-account --key-file=$GITHUB_WORKSPACE/credentials.json

      - name: Set Environment Variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "FLY_APP=datakoen-dev" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "FLY_APP=datakoen" >> $GITHUB_ENV
          fi

      - name: Install Fly.io CLI
        env:
          FLYCTL_INSTALL: /home/runner/.fly
          PATH: $FLYCTL_INSTALL/bin:$PATH
        run: |
          curl -L https://fly.io/install.sh | sh 

      - name: Set Fly.io Secrets
        env:
          FLY_TOKEN: ${{ secrets.FLY_TOKEN }}
        run: |
          flyctl secrets set TOGETHER_API_KEY=${{ secrets.TOGETHER_KEY }} hf_token=${{ secrets.HF_TOKEN }} --app $FLY_APP

      - name: Deploy to Fly.io
        env:
          FLY_TOKEN: ${{ secrets.FLY_TOKEN }}
        run: |
          flyctl deploy --config fly.toml --app $FLY_APP
