name: Code Check

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Analysing the code with pylint
      run: |
        tox 
  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - uses: actions/checkout@v3
    - name: Build docker images
      run: echo "Build docker image..." 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to fly.io
      run: echo "Deploying to fly.io..."