name: Deploy

on:
   push:
    branches:
      - main

jobs:
  move-rename:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CRED}}'